[project]
name = "smart-letterbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "paho-mqtt>=2.1.0",
    "requests>=2.32.3",
]
